feat(MOPLAT-335): Show artwork in CMS
artsy/energy pull request #127
Opened 2022-08-01 15:26 UTC by patrinoua

### Description

This PR resolves []

Todo:
- Add the link
- Test?

### PR Checklist

- [ ] I tested my changes on **iOS** and **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

Need help with something? Have a look at our [docs], or get in touch with us.

[docs]: /docs/README.md

2022-08-05 14:06 UTC, patrinoua commented on src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
> +              uri: `https://cms-staging.artsy.net/artworks/${artworkData.artwork?.internalID}/edit`,
this is currently not working. We need to update metaphysics.

2022-08-05 14:23 UTC, pvinis requested changes

2022-08-05 14:23 UTC, pvinis commented on ios/Podfile
> +  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
i dont think we need this at all. where did tou find this?

2022-08-05 14:23 UTC, pvinis commented on android/settings.gradle
> +project(':react-native-webview').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-webview/android')
same for that

2022-08-05 14:41 UTC, rajsam003 commented on src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
> +  const [isWebViewVisible, toggleIsWebViewVisible] = useState(false)
```suggestion
  const [isWebViewVisible, setIsWebViewVisible] = useState(false)
```
As it's a setState function. I think its better to follow react pattern.

2022-08-05 14:43 UTC, rajsam003 commented on src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
> +            <Flex width={width - space(4)} height={height - 150} position="absolute">
Do we need space hook here. I remember we agreed to use space hook only for padding and margin, not for height and width.

2022-08-05 14:45 UTC, rajsam003 commented on android/app/src/main/java/com/energy/MainApplication.java
> +import com.reactnativecommunity.webview.RNCWebViewPackage;
Can we bring this import to the last line, so that facebook imports stay together?

2022-08-06 10:00 UTC, patrinoua commented on ios/Podfile
> +  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
I needed to do some linking in order to get this to work but I will try again to see if it works without these!

2022-08-06 10:04 UTC, patrinoua commented on src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
> +            <Flex width={width - space(4)} height={height - 150} position="absolute">
The use of space here is accounting for margin space. The width is given by {width}

2022-08-06 10:05 UTC, patrinoua commented on src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
> +            <Flex width={width - space(4)} height={height - 150} position="absolute">
But we could also add it as a margin 😁

2022-08-06 10:05 UTC, patrinoua commented on src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
> +            <Flex width={width - space(4)} height={height - 150} position="absolute">
We want the width to be [fullwidth - something]

2022-08-06 10:06 UTC, patrinoua commented on src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
> +            <Flex width={width - space(4)} height={height - 150} position="absolute">
but I'll probably make a new screen to navigate to

2022-08-06 10:12 UTC, patrinoua commented on jest.config.js
> +      "|react-native-webview" +
It was breaking and by googling I came to this solution.

> The [transformIgnorePatterns](https://jestjs.io/docs/configuration#transformignorepatterns-arraystring) option can be used to specify which files shall be transformed by Babel. Many react-native npm modules unfortunately don't pre-compile their source code before publishing.

source https://jestjs.io/docs/tutorial-react-native#transformignorepatterns-customization

2022-08-08 11:38 UTC, patrinoua commented
replaced by https://github.com/artsy/energy/pull/130/files

2022-08-08 11:38 UTC, closed without merging