refactor: remove useSafeAreaInsets() | export header height
artsy/energy pull request #128
Opened 2022-08-02 13:40 UTC by rajsam003

This PR 

- removes the usage of `useSafeAreaInsets()` wherever possible and adds only to the header component. 
- Exports header height to use on different files

### PR Checklist

- [ ] I tested my changes on **iOS** and **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

Need help with something? Have a look at our [docs], or get in touch with us.

[docs]: /docs/README.md

2022-08-02 13:44 UTC, rajsam003 commented on src/app/screens/HomeTabs/Settings/DarkModeSettings.tsx
> -      <Text variant="lg">Dark Mode Settings</Text>
Lets use shared/UI Header everywhere

2022-08-02 13:47 UTC, rajsam003 commented on src/app/screens/HomeTabs/HomeTabs.tsx
>            navigation.navigate("Settings")
We need to fix this type issue as well.

2022-08-03 12:58 UTC, pvinis requested changes

2022-08-03 12:58 UTC, pvinis commented on src/app/sharedUI/Header.tsx
> +      <Flex height={HEADER_HEIGHT} justifyContent="center">
these two should be combined. we should not have anything wrapping the Flex with the `height` prop.

2022-08-03 12:58 UTC, pvinis commented on src/app/wrappers/TabsContainer.tsx
> +      <>
good stuff!

2022-08-03 14:55 UTC, rajsam003 commented on src/app/sharedUI/Header.tsx
> +      <Flex height={HEADER_HEIGHT} justifyContent="center">
Oh yes. Good catch.

2022-08-03 15:06 UTC, rajsam003 commented on src/app/sharedUI/Header.tsx
> +      <Flex height={HEADER_HEIGHT} justifyContent="center">
But we have header height 44 only for the back button, not for the label. So If we combine both flexes then the label flex gets messed up.  
On the artwork screen, we just import the back button height as the header height, as the screen doesn't contain any label/title. So I think it's better this way. 
Does it make sense?

2022-08-05 11:31 UTC, patrinoua commented on src/app/wrappers/TabsContainer.tsx
> +      <>
is this <> really necessary?

2022-08-05 11:33 UTC, pvinis commented on src/app/wrappers/TabsContainer.tsx
> +      <>
haha interesting. in that specific case here, no. i commented on the rest of them, but i guess i picked the one that actually doesn't need to be there 😅

2022-08-05 11:34 UTC, patrinoua commented on src/app/wrappers/TabsContainer.tsx
> +      <>
hihi 😄 so I guess we can remove this and merge, it looks good!

2022-08-05 11:37 UTC, pvinis commented on src/app/wrappers/TabsContainer.tsx
> +      <>
we will pair with sam now for a bit. we can remove this, and we need to check some flex combinations

2022-08-08 09:45 UTC, merged