feat( MOPLAT-335): Artwork: Open artwork in CMS - step by step
artsy/energy pull request #130
Opened 2022-08-08 11:17 UTC by patrinoua

### Description

This PR resolves [MOPLAT-335]

Follow up: add the right link, updates to metaphysics are required.
### PR Checklist
- [ ] I tested my changes on **iOS** and **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
### To the reviewers 👀
- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.
Need help with something? Have a look at our [docs], or get in touch with us.
[docs]: /docs/README.md
[
MOPLAT-335]: https://artsyproduct.atlassian.net/browse/
MOPLAT-335

2022-08-08 11:38 UTC, patrinoua commented
@pvinis @rajsam003 thank you for reviewing https://github.com/artsy/energy/pull/127. 

Since there were quite some questions/suggestions I went ahead and implemented this from scratch so I can provide some more context step-to-step on why some things were added.

When using WebView we need to link it and run pod install. [here](https://www.educative.io/answers/how-to-use-webview-in-react-native) is some more info about that, although they don't go much into details.

Otherwise we are getting this error
![Screen Shot 2022-08-08 at 13 08 32](https://user-images.githubusercontent.com/36475005/183409392-04fbf77c-db5b-415d-9920-5697b2e7275f.png)

Some info about this also here https://stackoverflow.com/questions/61832232/invariant-violation-requirenativecomponent-rncwebview-was-not-found-in-the-u

2022-08-08 11:41 UTC, patrinoua commented on src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
> +            icon={<EditIcon fill="white100" width="25" height="25" />}
@pvinis I would love us to have different size variations for our icons, eg "small" "medium" "large" as well as a default size (eg medium) so that we don't always pass these numbers hardcoded. What do you think?

2022-08-08 11:42 UTC, patrinoua commented on src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
> +            icon={<EditIcon fill="white100" width="25" height="25" />}
We could have a wrapper <Icon> component that does that

2022-08-08 12:00 UTC, rajsam003 approved these changes
LGTM

2022-08-08 12:50 UTC, pvinis requested changes

2022-08-08 12:50 UTC, pvinis commented on ios/Podfile
> +  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
can you try pod installing but without this line? i really think this is not needed here.

2022-08-08 12:55 UTC, pvinis commented on src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
> +            icon={<EditIcon fill="white100" width="25" height="25" />}
i would first ask our designers, as this is totally their decision. If we only need small or large in a couple of places, maybe its not worth making all icons have three scales, and we can just do what you did here.

2022-08-08 12:56 UTC, pvinis commented on src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
> +                uri: `https://cms-staging.artsy.net/artworks/${artworkData.artwork?.internalID}/edit`,
this works now, without the partnerid param?

2022-08-08 14:50 UTC, patrinoua commented on ios/Podfile
> +  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
This was automatically added when running the commands, I did not add it manually. I can manually remove it but then please test this PR locally to make sure it runs properly without this.

2022-08-08 15:26 UTC, patrinoua commented on src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
> +                uri: `https://cms-staging.artsy.net/artworks/${artworkData.artwork?.internalID}/edit`,
added 🙌🏻

2022-08-08 19:32 UTC, brainbicycle commented
I pushed a couple small changes:
- I added a header with a back button, without this can't get back to the app from the webview
- I changed the url to use slug instead of internal id, this works after authenticating the first time

One minor follow-up:
- We should probably steal the loading indicator from Eigen's webview, sorry this was overlooked in the ticket but it just shows a white screen while loading, I'll create a ticket for that

2022-08-09 09:56 UTC, patrinoua commented
@brainbicycle thanks!!

2022-08-09 09:58 UTC, pvinis commented
before merging, let's check if we can remove the podfile and android changes.

2022-08-09 16:10 UTC, patrinoua commented
replaced by https://github.com/artsy/energy/pull/133

2022-08-09 16:10 UTC, closed without merging