feat(moplat-262): better centering
artsy/energy pull request #131
Opened 2022-08-08 12:09 UTC by patrinoua

### Description

This PR resolves [moplat-262]

![Screen Shot 2022-08-08 at 14 09 02](https://user-images.githubusercontent.com/36475005/183414642-0afa6a7a-99ae-4624-8ad4-841805eeb30e.png)

### PR Checklist

- [ ] I tested my changes on **iOS** and **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

Need help with something? Have a look at our [docs], or get in touch with us.

[docs]: /docs/README.md

2022-08-08 12:47 UTC, pvinis requested changes

2022-08-08 12:47 UTC, pvinis commented on src/app/sharedUI/screens/InstallImage/InstallImage.tsx
> +      <Flex px={2} pt={insets.top} position="absolute">
this should use our shared `Header`

2022-08-08 16:31 UTC, patrinoua commented on src/app/sharedUI/screens/InstallImage/InstallImage.tsx
> +      <Flex px={2} pt={insets.top} position="absolute">
done :)

2022-08-09 10:04 UTC, pvinis approved these changes
nice. thanks!

2022-08-09 10:07 UTC, merged