perf: Replacing artwork(id) with artworks query
artsy/energy pull request #146
Opened 2022-08-25 13:19 UTC by rajsam003

This PR improves the performance of the app by fetching all artworks at once instead of nesting query renderers for the albums. 

Before: 
```
artwork(id: $id) {
      ...ArtworkGridItem_artwork
    }

```

After:
```
artworks(ids: [id1, id2, id3, ...]) {
      edges{
           node{
          ...ArtworkGridItem_artwork
          }
       }
    }
```

### PR Checklist

- [x] I tested my changes on **iOS** and **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

Need help with something? Have a look at our [docs], or get in touch with us.

[docs]: /docs/README.md

2022-08-25 13:27 UTC, rajsam003 commented on src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
> +
@mdole Here is the case I was talking about☝️

2022-08-25 13:33 UTC, MounirDhahri reviewed
Nice PR Sam, thanks for making this change ❤️ I left a small comment, let me know if you didn't get what I mean

2022-08-25 13:33 UTC, MounirDhahri commented on src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
> +  /* If we pass empty ids(selectedArtworks) as parameter in the albumArtworksQuery API,
**praise:** thanks for the comment, it makes it easier to understand your reasoning here.

2022-08-25 13:33 UTC, MounirDhahri commented on src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
> +  /* If we pass empty ids(selectedArtworks) as parameter in the albumArtworksQuery API,
**suggestion:** I am wondering though if a hotfix is what we need here, I would suggest here to add a new argument to the interface (`allowEmptyReturns` or something like that) to let it know to return nothing if nothing is provided. This way we can fix the problem everywhere in Artsy and make the next dev life a bit easier

Speaking of making a change here https://www.notion.so/artsy/Sprint-17-cdd05a12330e4b27b9c2ba16a8a9d812

2022-08-26 10:40 UTC, patrinoua commented on src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
> +    it returns random artworks(instead of returning empty object),
Wow this sounds bad! Thoughts @brainbicycle @mc-jones @lidimayra ?

2022-08-26 10:54 UTC, rajsam003 commented on src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
> +    it returns random artworks(instead of returning empty object),
We already have a thread for this
https://artsy.slack.com/archives/CP9P4KR35/p1661419259015689

2022-08-26 13:05 UTC, brainbicycle commented on src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
> +    it returns random artworks(instead of returning empty object),
hmmm, it sounds like weird behavior by the api to me but also if we don't have artwork ids I think it makes sense not to query the api at all? so the frontend guard against that condition seems like enough to me

2022-08-26 13:08 UTC, brainbicycle commented on src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
> +    it returns random artworks(instead of returning empty object),
but I actually think the bigger concern from that thread is the endpoint is deprecated so we may not want to use this at all in folio?

2022-08-26 13:26 UTC, brainbicycle requested changes
Thanks Sam for thinking about the performance here! I think unfortunately we may want to keep it as is for now because from the thread it sounds like this endpoint is deprecated. It is possible we could use artworksConnection or filterArworksConnection for the same purpose but I would suggest holding off until we have a better sense of what offline access looks like. Reason being if offline ends up requiring fetching all data up front that might dictate which endpoints we use and also would mean that once fetched going to a page would be instant.

2022-08-26 14:34 UTC, rajsam003 commented
> Thanks Sam for thinking about the performance here! I think unfortunately we may want to keep it as is for now because from the thread it sounds like this endpoint is deprecated. It is possible we could use artworksConnection or filterArworksConnection for the same purpose but I would suggest holding off until we have a better sense of what offline access looks like. Reason being if offline ends up requiring fetching all data up front that might dictate which endpoints we use and also would mean that once fetched going to a page would be instant.

Makes total sense Brian

2022-09-01 12:47 UTC, rajsam003 commented
> Should we close this pr?

Ya sure. I am closing it.

2022-09-01 12:47 UTC, closed without merging