feat(MOPLAT-394): Share sheet for artwork screen
artsy/energy pull request #154
Opened 2022-08-29 13:31 UTC by patrinoua

### Description

This PR resolves [MOPLAT-394]

- Add bottom modal
- dismiss by clicking X or background
- navigate to "Add to Album" and "Edit Artwork in CMS"

https://user-images.githubusercontent.com/36475005/187454932-b4d5a8f3-b39c-463e-af28-b51d03e1cdc6.mov

### PR Checklist

- [ ] I tested my changes on **iOS** and **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

Need help with something? Have a look at our [docs], or get in touch with us.

[docs]: /docs/README.md

[MOPLAT-394]: https://artsyproduct.atlassian.net/browse/MOPLAT-394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2022-08-30 14:01 UTC, patrinoua commented on src/app/sharedUI/screens/Artwork/Artwork.tsx
> +            }}
this looks weird (combo of Touchable and Flex!), I know! 
It was the only way to get it to work after experimenting with it... 🙈

2022-08-30 16:10 UTC, rajsam003 commented
![image](https://user-images.githubusercontent.com/17421923/187487125-250481ac-8c72-4254-9ac4-dc272b883166.png)
Can you fix this padding please?

2022-08-30 16:13 UTC, rajsam003 commented
Also the touchable active color and Header on the next screen.
https://user-images.githubusercontent.com/17421923/187487531-188d6a6a-1ab6-496a-9465-03cd055d8e56.mov

2022-08-31 11:41 UTC, patrinoua commented
@rajsam003 thanks for the feedback, I just pushed some changes can you have another look and merge if it looks ok?

2022-08-31 12:16 UTC, rajsam003 commented on src/app/screens/HomeTabs/HomeTabs.tsx
> +  const navigation = useNavigation()
These changes are not related to this ticket.

2022-08-31 12:16 UTC, rajsam003 commented on src/app/screens/HomeTabs/Settings/Settings.tsx
> +        <Button block onPress={() => navigation.navigate("InsteadOfStorybook")}>
same for this file

2022-08-31 12:23 UTC, patrinoua commented on src/app/screens/HomeTabs/Settings/Settings.tsx
> +        <Button block onPress={() => navigation.navigate("InsteadOfStorybook")}>
I know but they are small changes for the consistency of naming of variables around the app. Would you like me to make a ticket for this?

2022-08-31 12:50 UTC, pvinis commented on src/app/sharedUI/Header.tsx
> +          <Touchable onPress={() => navigation.goBack()} underlayColor="transparent">
not blocking, since we will fix it later, but is this giving any visual feedback when pressed?

2022-08-31 12:51 UTC, pvinis commented on src/app/sharedUI/screens/Artwork/Artwork.tsx
> +            }}
it doesn't look weird, it's fine 👍.

touchable is a bit funky with it's layout, I have seen that elsewhere too. good work figuring it out.

2022-08-31 12:52 UTC, rajsam003 commented on src/app/sharedUI/screens/Artwork/Artwork.tsx
> +          <Flex position="relative" alignItems="center" justifyContent="center" height="50">
By default flex has position: relative
```suggestion
          <Flex alignItems="center" justifyContent="center" height="50">
```

2022-08-31 12:53 UTC, rajsam003 commented on src/app/sharedUI/screens/Artwork/Artwork.tsx
> +        <Flex width="10%" alignItems="center" justifyContent="center">
Lets avoid adding percentages value. 
```suggestion
        <Flex px={1} alignItems="center" justifyContent="center">
```

2022-08-31 12:54 UTC, pvinis commented on src/app/sharedUI/screens/Artwork/Artwork.tsx
> +  navigateTo: () => void
two things for this:
- I see we have navigateTo={()=>{}}, why not make this prop optional and avoid the empty funcs?
- could we just have useNavigation inside the ModalRow or would that be strange?

2022-08-31 12:55 UTC, rajsam003 commented
Good work Angela, I have just added some small suggestions. 
Also the alignment looks good but the `Edit artwork in CMS` button is getting cropped in bottom
![image](https://user-images.githubusercontent.com/17421923/187683075-e47dff76-48db-469f-a0d3-ce25afb2580b.png)

2022-08-31 12:56 UTC, pvinis commented on src/app/screens/HomeTabs/Settings/Settings.tsx
> +        <Button block onPress={() => navigation.navigate("InsteadOfStorybook")}>
it's ok, small change, and pretty simple one. we can allow these I think.

2022-08-31 13:02 UTC, pvinis commented on src/app/sharedUI/screens/Artwork/Artwork.tsx
> +        <Flex width="10%" alignItems="center" justifyContent="center">
these two mean very different things. what's the part of the design for this? let's see which one we want.

2022-08-31 13:09 UTC, patrinoua commented on src/app/sharedUI/Header.tsx
> +          <Touchable onPress={() => navigation.goBack()} underlayColor="transparent">
Nope

2022-08-31 13:10 UTC, patrinoua commented on src/app/sharedUI/screens/Artwork/Artwork.tsx
> +        <Flex width="10%" alignItems="center" justifyContent="center">
I just tried to imitate the design which looks like this https://www.figma.com/proto/BQVn5aOJ4varTAgtz8mnai/Folio-2022?page-id=1312%3A3966&node-id=1649%3A11168&viewport=-1879%2C2704%2C0.36&scaling=scale-down&starting-point-node-id=1649%3A10878&show-proto-sidebar=1

2022-08-31 13:11 UTC, patrinoua commented on src/app/sharedUI/screens/Artwork/Artwork.tsx
> +  navigateTo: () => void
This is how I started this but it was strange with passing down props

2022-08-31 14:49 UTC, patrinoua commented on src/app/sharedUI/screens/Artwork/Artwork.tsx
> +        <Flex width="10%" alignItems="center" justifyContent="center">
What is the problem with % values? 🤔

2022-08-31 15:20 UTC, rajsam003 commented on src/app/sharedUI/screens/Artwork/Artwork.tsx
> +        <Flex width="10%" alignItems="center" justifyContent="center">
I remember that we like to avoid having places in the app where we have padding to be 20 pixels, then somewhere else where it’s 35pilxels (for a phone that’s 350pixels and with a padding of 10%). We want users to get used to having the same padding everywhere across the app.

2022-08-31 15:24 UTC, rajsam003 commented on src/app/sharedUI/screens/Artwork/Artwork.tsx
> +        <Flex width="10%" alignItems="center" justifyContent="center">
I just like to follow the same approach. I would prefer using padding and margin values for FLex instead of width and height.

2022-08-31 15:38 UTC, pvinis commented on docs/troubleshooting.md
> +cd ios ; pod install ; bundle install
this is done by install:all, no?

2022-08-31 15:38 UTC, pvinis commented on src/app/sharedUI/screens/Artwork/Artwork.tsx
> +        <Flex width="10%" alignItems="center" justifyContent="center">
that could be a good discussion for practice

2022-08-31 15:38 UTC, pvinis commented on src/app/sharedUI/screens/Artwork/Artwork.tsx
> +          <ModalRow Icon={<EditIcon />} label="Send by Email" navigateTo={() => {}} />
that's the empty funcs I mean

2022-08-31 15:49 UTC, patrinoua commented on src/app/sharedUI/screens/Artwork/Artwork.tsx
> +        <Flex width="10%" alignItems="center" justifyContent="center">
How about we keep the 10% width so that we can assign 10% to the first element, 80% to the second and 10% to the third, but remove horizontal "center" and add a padding to the left and the right? Would that be ok?

2022-08-31 15:54 UTC, patrinoua commented on src/app/sharedUI/screens/Artwork/Artwork.tsx
> +          <ModalRow Icon={<EditIcon />} label="Send by Email" navigateTo={() => {}} />
These are empty right now but they will be filled once we add this functionality. So this will then be a simple replace of the empty function with the navigate function.

2022-09-01 07:19 UTC, rajsam003 commented
> > Good work Angela,
> > I have just added some small suggestions.
> > Also the alignment looks good but the `Edit artwork in CMS` button is getting cropped in bottom
> > ![image](https://user-images.githubusercontent.com/17421923/187683075-e47dff76-48db-469f-a0d3-ce25afb2580b.png)
> 
> Thank you, which device is this?

IPhone 8 simulator

2022-09-01 07:43 UTC, pvinis requested changes
ok lets change the % and remove the cd ios podinstall stuff, and i think we are good to go?

2022-09-01 07:43 UTC, pvinis commented on src/app/sharedUI/screens/Artwork/Artwork.tsx
> +        <Flex width="10%" alignItems="center" justifyContent="center">
ah now i see the figma link. ok so basically you had 10% of the width on the icon. yea i agree with sam, there is no need for a percentage here. the icon is a specific size, so we should use that as the width and height for this flex. using a percentage will mean that it looks different on wider and narrower phones/ipads, and thats not what we want.

2022-09-01 07:43 UTC, pvinis commented on src/app/sharedUI/screens/Artwork/Artwork.tsx
> +          <ModalRow Icon={<EditIcon />} label="Send by Email" navigateTo={() => {}} />
gotcha. good to go then. still feels like `onPress` where its an optional thing, but its fine 👍

2022-09-01 10:45 UTC, pvinis approved these changes

2022-09-01 11:08 UTC, merged

2022-09-01 12:10 UTC, patrinoua commented
🚀 🎉 🎉 🎉