WIP feat(MOPLAT-352): Util function to retrieve the right size for artworks
artsy/energy pull request #165
Opened 2022-08-31 09:35 UTC by patrinoua

### Description

This PR resolves [MOPLAT-352]

### PR Checklist
- [ ] I tested my changes on **iOS** and **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
### To the reviewers 👀
- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

Need help with something? Have a look at our [docs], or get in touch with us.

[docs]: /docs/README.md

2022-09-01 06:53 UTC, rajsam003 commented on src/__generated__/ArtistArtworksQuery.graphql.ts
> +    resized(version: "normalized") {
**non-blocking** - Is .gitignore not working for you?

2022-09-01 07:15 UTC, rajsam003 commented on src/app/utils/imageSize.ts
> +export const imageSize = 2 * windowWidth * pixelRatio
**thought**: This calculation has nothing to do with image so I dont think `imageSize` is a good name. May be `screenWidth` or `screenSize`.

2022-09-01 07:17 UTC, rajsam003 commented on src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
> +        resized(height: $imageSize, version: "normalized") {
**question**: We are calculating for `width` and passing it for height. Did you try passing it for width. I mean - `resized(width: $imageSize, version: "normalized")`

2022-09-01 12:21 UTC, patrinoua commented on src/__generated__/ArtistArtworksQuery.graphql.ts
> +    resized(version: "normalized") {
probably not! Strange right?

2022-09-01 12:24 UTC, patrinoua commented on src/app/utils/imageSize.ts
> +export const imageSize = 2 * windowWidth * pixelRatio
It is the imageSize we wish for. It uses screen width, but it is not screen width or screen size.  Or if you think it is better we can rename it to "calculatedImageWidthForDoublePersision" but that could be a little bit of an overkill, so we may as well just keep "imageSize" as a convention.

Open to suggestions anyone has a better name idea! 🤷🏻‍♀️

2022-09-01 12:25 UTC, patrinoua commented on src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
> +        resized(height: $imageSize, version: "normalized") {
Good point, I've updated that to use the window height instead

 
![Screen Shot 2022-09-01 at 14 24 43](https://user-images.githubusercontent.com/36475005/187913132-a71bb181-da8d-4317-8a83-02a230f338fc.png)

2022-09-01 12:41 UTC, rajsam003 commented on src/__generated__/ArtistArtworksQuery.graphql.ts
> +    resized(version: "normalized") {
Yes👀. For me, it's working fine.

2022-09-01 12:42 UTC, rajsam003 approved these changes
Good work and thanks for addressing my comments :) 
🚀

2022-09-01 16:07 UTC, admbtlr commented on src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
> +        resized(height: $imageSize, version: "normalized") {
Pretty sure we want to use windowWidth here, not windowHeight

2022-09-01 16:11 UTC, admbtlr requested changes

2022-09-01 16:11 UTC, admbtlr commented on src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
> +        resized(height: $imageSize, version: "normalized") {
It's line 313 that should change here: 
```suggestion
        resized(width: $imageSize, version: "normalized") {
```

2022-09-01 16:11 UTC, admbtlr commented on src/app/utils/imageSize.ts
> +export const imageSize = 2 * windowHeight * pixelRatio
And then this should go back to using `windowWidth` instead of `windowHeight`

2022-09-02 07:19 UTC, patrinoua commented on src/app/utils/imageSize.ts
> +export const imageSize = 2 * windowHeight * pixelRatio
I am happy to update this, however I am curious, since we are not checking if width or height is bigger and this may differ from one image to the other, why do we prefer width over height? 
It felt like an axiomatic choice but curious to see if there is a reasoning behind this.

2022-09-06 14:18 UTC, patrinoua commented on src/app/utils/imageSize.ts
> +export const imageSize = 2 * windowHeight * pixelRatio
Thanks. I've updated to use width, feel free to merge if it's ok.

2022-09-09 11:05 UTC, pvinis commented on src/app/utils/imageSize.ts
> +export const imageSize = 2 * windowWidth * pixelRatio
non blocking, but i would prefer `calculatedImageWidthForDoublePersision` to be honest, because `imageSize` is a name that could appear naturally in our code, and i wouldn't want my editor to start importing stuff for me when i don't need them.

2022-09-09 11:08 UTC, pvinis approved these changes

2022-09-09 11:09 UTC, pvinis commented
merge when ready 👍. i assigned it back to you. thanks!

2022-09-09 13:22 UTC, admbtlr commented on src/app/utils/imageSize.ts
> +export const imageSize = 2 * windowWidth * pixelRatio
good point - but I guess you mean `calculatedImageWidthForDoublePrecision`?

2022-09-12 10:37 UTC, merged