refactor: Replacing ternary with &&
artsy/energy pull request #166
Opened 2022-08-31 11:18 UTC by rajsam003

This PR replaces the usage of the ternary operator with && for rendering components

### PR Checklist

- [ ] I tested my changes on **iOS** and **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

Need help with something? Have a look at our [docs], or get in touch with us.

[docs]: /docs/README.md

2022-08-31 11:28 UTC, patrinoua approved these changes

2022-08-31 11:30 UTC, pvinis commented on src/app/sharedUI/items/ArtworkGridItem.tsx
> +      {selectedToRemove && (
this is not a strict boolean, so we should not do that here.

2022-08-31 11:30 UTC, pvinis commented on src/app/sharedUI/items/ArtworkGridItem.tsx
> +      {!disable && selectedToAdd && (
same.

2022-08-31 11:30 UTC, pvinis commented on src/app/sharedUI/items/ArtworkGridItem.tsx
> +      {selectedToRemove && (
actually, maybe we can quickly enable the eslint rule for this? let me find the one i mean.

2022-08-31 11:31 UTC, MounirDhahri commented on src/app/sharedUI/items/ArtworkGridItem.tsx
> +      {!disable && selectedToAdd && (
do we check for this in our config?

2022-08-31 11:33 UTC, pvinis commented on src/app/sharedUI/items/ArtworkGridItem.tsx
> +      {!disable && selectedToAdd && (
not yet. ill try to add this now quickly, before we start making bugs :D

2022-08-31 12:21 UTC, pvinis commented on src/app/sharedUI/items/ArtworkGridItem.tsx
> +      {!disable && selectedToAdd && (
ok ill push a new PR and we can rebase this on top

2022-08-31 12:21 UTC, pvinis commented on src/app/sharedUI/items/ArtworkGridItem.tsx
> +      {selectedToRemove && (
this would be ok if we do 
```suggestion
      {selectedToRemove === true && (
```

2022-09-01 14:43 UTC, MounirDhahri commented on src/app/sharedUI/items/ArtworkGridItem.tsx
> +      {!disable && selectedToAdd && (
awesome, thanks Pavlos

2022-09-06 12:20 UTC, patrinoua requested changes

2022-09-06 12:20 UTC, patrinoua commented on src/app/navigation/HomeTabsNavigationStack.tsx
> +        <Flex
These do not exist on the latest main, let's maybe rebase

2022-09-06 14:51 UTC, MounirDhahri commented on src/app/screens/HomeTabs/Albums/AlbumArtworks.tsx
> +        renderItem={({ item: artworkId }: { item: string }) => (
**thought:** Ideally you shouldn't need to specify the type of the item here since it should be already interpreted from the data object - if not, something might be wrong somewhere

2022-09-06 14:51 UTC, MounirDhahri commented on src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
> +        renderItem={({ item: artworkId }: { item: string }) => {
same comment here as above about adding the item type

2022-09-06 14:51 UTC, MounirDhahri commented on src/app/screens/HomeTabs/Settings/Settings.tsx
> +        <Button block onPress={() => GlobalStore.actions.auth.signOut() as void}>
**suggestion:** maybe we can use this pattern instead to avoid casting
```suggestion
        <Button block onPress={() => {
        GlobalStore.actions.auth.signOut()
        }}>
```

2022-09-06 14:51 UTC, MounirDhahri commented on src/app/screens/HomeTabs/Albums/AlbumArtworks.tsx
> +        renderItem={({ item: artworkId }: { item: string }) => (
the same pattern is used few times, i think we should adjust it in other places as well

2022-09-06 22:19 UTC, pvinis commented on src/app/screens/HomeTabs/Settings/Settings.tsx
> +        <Button block onPress={() => GlobalStore.actions.auth.signOut() as void}>
```suggestion
        <Button block onPress={() => void GlobalStore.actions.auth.signOut()}>
```
this is another option too, without casting.

2022-09-06 22:20 UTC, pvinis commented on src/app/screens/HomeTabs/Shows/ShowTabs/ShowArtworks/ShowArtworks.tsx
> +        renderItem={({ item: artwork }: { item: typeof artworks[number] }) => (
kinda weird this is needed. maybe `MasonryList` has bad types? we could take a look together.

2022-09-06 22:32 UTC, pvinis commented on src/app/screens/Auth/Login.tsx
> +      })) as { success: boolean; message: string }
why is this type needed? this type should be in the `signInUsingEmail`.

2022-09-06 22:32 UTC, pvinis commented on src/app/screens/Auth/SelectPartner.tsx
> -const partnerQuery = graphql`
not blocking, but whats the reasoning behind this change here?

2022-09-07 09:08 UTC, MounirDhahri commented on src/app/screens/HomeTabs/Settings/Settings.tsx
> +        <Button block onPress={() => GlobalStore.actions.auth.signOut() as void}>
🤓 I haven't seen this before- thanks for the suggestion @pvinis

2022-09-07 10:29 UTC, rajsam003 commented on src/app/screens/Auth/SelectPartner.tsx
> -const partnerQuery = graphql`
Its just rebase change 😁

2022-09-08 09:41 UTC, pvinis approved these changes
perfect. thanks!

2022-09-08 09:44 UTC, pvinis approved these changes
merge when green 👍. assigning this back to you.

2022-09-08 10:35 UTC, merged