feat(MOPLAT-406): Shallow zoom for artworks and install shots - ReactNativeZoomableView
artsy/energy pull request #186
Opened 2022-09-09 10:48 UTC by patrinoua

### Description

This PR resolves [MOPLAT-406]

https://user-images.githubusercontent.com/36475005/189333557-786e762a-3829-4cca-bb54-e07d02cf5c39.mov

### PR Checklist
- [ ] I tested my changes on **iOS** and **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
### To the reviewers 👀
- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

Need help with something? Have a look at our [docs], or get in touch with us.

[docs]: /docs/README.md

2022-09-09 13:41 UTC, admbtlr commented
Nice! Couple of things:

- can you make the background just use the background colour?
- can you make sure the image is vertically centred?
- can you skip the animation from the bottom, and just have it appear directly over the top?
- can we restrict the zoom level so that the images don't pixelate? Once the image util function is merged, we should be able to zoom to 2x without any pixellation.

2022-09-09 14:03 UTC, patrinoua commented
@admbtlr thanks for the feedback, I've just updated the PR, uploading a video too.

2022-09-09 14:10 UTC, patrinoua commented
done

2022-09-09 15:17 UTC, admbtlr commented on src/app/sharedUI/molecules/ImageModal.tsx
> +    <Flex backgroundColor="background" flex={1} pt={6} px={2}>
I think you need to use `safeAreaInsets` or something similar, rather than hardcoding `pt={6}`, since this doesn't work on devices without a notch.

2022-09-09 15:22 UTC, patrinoua commented on src/app/sharedUI/molecules/ImageModal.tsx
> +    <Flex backgroundColor="background" flex={1} pt={6} px={2}>
oh yes thanks, I've updated it.

2022-09-12 10:17 UTC, rajsam003 commented on src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
> +  const [modalVisible, setModalVisible] = useState(false)
same

2022-09-12 11:00 UTC, pvinis commented on src/app/sharedUI/molecules/ImageModal.tsx
> +      <Flex backgroundColor="background" flex={1} pt={insets.top} px={2}>
```suggestion
      <Flex backgroundColor="background" flex={1} pt={insets.top}>
```

i think this is not needed, so the image takes full width of screen?

2022-09-12 11:00 UTC, pvinis commented on src/app/sharedUI/molecules/ImageModal.tsx
> +        <ReactNativeZoomableView maxZoom={2} contentWidth={300} contentHeight={150}>
where do these numbers come from? 300 and 150?

2022-09-12 11:05 UTC, pvinis requested changes

2022-09-12 11:05 UTC, pvinis commented on src/palette/atoms/BackButton/BackButton.tsx
> +  fill,
i dont see a use for this. you use it with the default anyway in this PR. also, I don't see a use for a back button with a different color 🤔.

2022-09-12 11:05 UTC, pvinis commented on src/palette/atoms/BackButton/BackButton.tsx
> +  absolute,
i dont think this should be here. i see the back button is added on the modal. I would much rather have a flex absolute in that modal, that has a back button as a child. adding this to the button just screams for future issues right now.

2022-09-12 12:58 UTC, patrinoua commented
@rajsam003 @pvinis thank you for your feedback! I've updated the pr, feel free to merge if it's ok.

2022-09-13 09:29 UTC, patrinoua commented on src/app/sharedUI/molecules/ImageModal.tsx
> +    <Flex backgroundColor="background" flex={1} pt={6} px={2}>
Addressed, resolving conversation 🙌🏻

2022-09-13 09:29 UTC, patrinoua commented on src/app/sharedUI/items/ArtworkImageGridItem.tsx
> +  const [modalVisible, setModalVisible] = useState(false)
Addressed, resolving conversation 🙌🏻

2022-09-13 09:29 UTC, patrinoua commented on src/app/sharedUI/molecules/ImageModal.tsx
> +      <Flex backgroundColor="background" flex={1} pt={insets.top} px={2}>
Addressed, resolving conversation 🙌🏻

2022-09-13 09:30 UTC, patrinoua commented on src/app/sharedUI/molecules/ImageModal.tsx
> +        <ReactNativeZoomableView maxZoom={2} contentWidth={300} contentHeight={150}>
Addressed, resolving conversation 🙌🏻

2022-09-13 09:30 UTC, patrinoua commented on src/palette/atoms/BackButton/BackButton.tsx
> +  fill,
Addressed, resolving conversation 🙌🏻

2022-09-13 09:30 UTC, patrinoua commented on src/palette/atoms/BackButton/BackButton.tsx
> +  absolute,
Addressed, resolving conversation 🙌🏻

2022-09-14 15:08 UTC, pvinis approved these changes

2022-09-14 15:11 UTC, merged