MOPLAT-417 Send Email pt 2: Send Artwork(s) via email
artsy/energy pull request #242
Opened 2022-09-30 15:42 UTC by patrinoua

### Description

This PR resolves [MOPLAT-417]

### PR Checklist
- [ ] I tested my changes on **iOS** and **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
### To the reviewers 👀
- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

Need help with something? Have a look at our [docs], or get in touch with us.

[docs]: /docs/README.md

2022-09-30 15:45 UTC, patrinoua commented on src/app/screens/HomeTabs/Artists/Artists.tsx
> +  navigation.navigate("ArtistTabs", {
let's remove this before merging

2022-09-30 15:45 UTC, patrinoua commented on src/app/screens/HomeTabs/Artists/ArtistTabs/ArtistArtworks/ArtistArtworks.tsx
> +  navigation.navigate("Artwork", {
let's remove this before merging

2022-10-06 08:21 UTC, brainbicycle commented on ios/Energy.xcodeproj/project.pbxproj
> -						DevelopmentTeam = 23KMWZ572J;
can we make sure we untoggle automatic code signing in Xcode before merging 🙏

2022-10-06 08:24 UTC, brainbicycle commented on src/app/sharedUI/screens/Artwork/Artwork.tsx
> +// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
**tangent, non-blocking:** I am seeing these pop up in my code as well, should we disable this rule? or is there a way to avoid it?

2022-10-06 08:29 UTC, brainbicycle commented on yarn.lock
> +expo@^45.0.0:
**thought, non-blocking**: it looks like using this expo dependency pulled in a ton of transitive dependencies and required a bunch of native code changes, I am wondering if there were any other non-expo email compose libraries that might be lighter? I don't know so much about expo so wondering if other have thoughts, maybe we will need it eventually anyway? @artsy/mobile-platform

2022-10-06 08:32 UTC, brainbicycle commented on src/app/sharedUI/screens/Artwork/Artwork.tsx
> +                  subject: `Information about "${title ? title : ""}" by ${
**suggestion**: if there are no artistnames maybe we probably shouldn't show `by` either could add it to the ternary below

2022-10-06 08:34 UTC, brainbicycle requested changes
some small change requests but looks good, larger question I have is about the expo dependency, it seems like a lot of requirements for an email compose library but maybe it is unavoidable, I will leave it to the rest of you who know more about expo. Nice work!

2022-10-06 08:38 UTC, pvinis commented on android/settings.gradle
> +useExpoModules()
just for a new line at the end

2022-10-06 08:40 UTC, pvinis commented on ios/Energy.xcodeproj/project.pbxproj
> -						DevelopmentTeam = 23KMWZ572J;
good point from @brainbicycle. we should edit this diff in this file.

changes that need to go are lines including:
- DevelopmentTeam
- ProvisioningStyle
- CODE_SIGN_STYLE
- PROVISIONING_PROFILE_SPECIFIER

everything else should stay. i think its basically these 4 lines. i can make gh suggestions if you like.

2022-10-06 08:41 UTC, pvinis commented on ios/Energy.xcodeproj/project.pbxproj
>  						LastSwiftMigration = 1120;
```suggestion
						DevelopmentTeam = 23KMWZ572J;
						LastSwiftMigration = 1120;
						ProvisioningStyle = Manual;
```

2022-10-06 08:43 UTC, pvinis commented on src/app/sharedUI/screens/Artwork/Artwork.tsx
> +                  body: bodyHTML,
i know i shouldnt, but im impressed with how well this works :D

2022-10-06 08:45 UTC, pvinis commented on src/app/sharedUI/screens/Artwork/Artwork.tsx
> +                  subject: `Information about "${title ? title : ""}" by ${
i guess this will come from the templates, right? so either we use the templates here, or we have a separate ticket and its ok to put whatever string here for now?

2022-10-06 08:50 UTC, admbtlr commented on yarn.lock
> +expo@^45.0.0:
Expo is a pretty huge dependency, and it can cause major headaches (although we've probably avoided the largest one, when they switched away from their unimodules system about 6 months ago). I would prefer not to use it unless there's no alternative.

2022-10-06 08:57 UTC, brainbicycle commented on yarn.lock
> +expo@^45.0.0:
It is easy to revert now but if it is there we start to take it for granted and rely on it for other dependencies and then it gets harder 😬 if there is an easy other option I would prefer to use it personally

2022-10-06 16:55 UTC, pvinis commented on src/app/sharedUI/screens/Artwork/Artwork.tsx
> +                  subject: `Information about "${title ? title : ""}" by ${
@patrinoua will make a separate PR for the templates, as part of the same ticket.

2022-10-06 16:57 UTC, pvinis commented
https://artsy.slack.com/archives/C02NAJ2CGLW/p1665073971939519 for the expo decision.

2022-10-06 16:59 UTC, merged

2022-10-06 16:59 UTC, pvinis commented
template to be worked on monday 👍