fix: presentation mode for price and tests cases
artsy/energy pull request #278
Opened 2022-10-19 10:14 UTC by rajsam003

This PR resolves [MOPLAT-450]

https://user-images.githubusercontent.com/17421923/196663522-c98b41a8-51a2-430e-9524-f275c8099505.mov

### PR Checklist

- [ ] I tested my changes on **iOS** and **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

Need help with something? Have a look at our [docs], or get in touch with us.

[docs]: /docs/README.md

2022-10-19 10:15 UTC, rajsam003 commented on src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
> -              {!(isPriceHidden && !price) && (
This was the real culprit

2022-10-19 10:21 UTC, pvinis commented on src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
>    const isPriceHidden = GlobalStore.useAppState((state) => state.presentationMode.hiddenItems.price)
```suggestion
  const showPrice = !GlobalStore.useAppState((state) => state.presentationMode.hiddenItems.price)
```
I wonder if that makes it clearer

2022-10-19 10:22 UTC, pvinis commented on src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
> +              {!!price && !isPriceHidden && (
```suggestion
              {!!price && showPrice && (
```
🤔?

2022-10-21 12:27 UTC, gkartalis commented on src/app/screens/HomeTabs/Shows/ShowTabs/ShowArtworks/ShowArtworks.tsx
> +import { useMemo } from "react"
**question:** is this used anywhere in this file? weird that the linter didn't catch it

2022-10-21 12:27 UTC, gkartalis commented on src/app/sharedUI/items/ArtworkGridItem.tests.tsx
> +    expect(container.findByType(Text).props.children[0].props).toBeTruthy()
**question:** What are you asserting on here?

Also if you are searching for some text to be in the document it is better to do so with `queryByText` from rntl
```suggestion
    expect(queryByText("my text")).toBeTruthy()
```

2022-10-21 12:27 UTC, gkartalis commented on src/app/sharedUI/items/ArtworkGridItem.tests.tsx
> +    expect(container.findByType(Text).props.children[0].props).toBeTruthy()
same for the assertions on the rest of the file

2022-10-21 12:27 UTC, gkartalis commented on src/app/sharedUI/items/ArtworkGridItem.tests.tsx
> +    expect(container.findByType(Text).props.children[0].props).toBeTruthy()
because the existing implementation makes sure that there is a `<Text />` element and then I don't understand what it is checking, that the text has props and the first prop has children with context props? 🤯

2022-10-21 12:29 UTC, pvinis requested changes
amazing work! i added some comments that I think we need to address before merge, but I really like your solution 👍

2022-10-21 12:29 UTC, pvinis commented on src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
> +  const presentedArtworks = getPresentedArtworks(artworks)
i still think we should make it obvious that this is a hook, otherwise I am afraid we would end up using in ifs or returns.

maybe `usePresentationFilteredArtworks` or `useGetPresentedArtworks` or `usePresentationFiltering` or something?

2022-10-21 12:29 UTC, pvinis commented on src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
> +    selectedArtworks.length > 0 ? extractNodes(artworksData.partner?.artworksConnection) : []
could you add a comment here about the reason we need this? something along the lines of "MP returns random artworks when the artworkIDs array is empty, so we just don't extract the results" or something?

2022-10-21 12:29 UTC, pvinis commented on src/app/screens/HomeTabs/getPresentedArtworks.ts
> +export const getPresentedArtworks = (
naming, as i said in the other comment.

2022-10-21 12:29 UTC, pvinis commented on src/app/screens/HomeTabs/getPresentedArtworks.ts
> +  }, [isNotForSaleHidden, isUnpublishedWorksHidden])
im pretty sure we need to add `artworks` in the dep list, right?

2022-10-21 12:29 UTC, pvinis commented on src/app/sharedUI/screens/Artwork/Artwork.tsx
> +              isLastRow={isEditArtworkHidden}
should the one above get the "isLastRow" then too?

2022-10-21 12:29 UTC, pvinis commented on src/app/sharedUI/items/ArtworkGridItem.tests.tsx
> +    const { container } = renderWithWrappers(<TestRenderer />)
```suggestion
    const { UNSAFE_findByType } = renderWithWrappers(<TestRenderer />)
```

you could totally use that instead. not blocking though.

2022-10-21 12:29 UTC, pvinis commented on src/app/sharedUI/items/ArtworkGridItem.tests.tsx
> +    expect(container.findByType(Text).props.children[0].props).toBeUndefined()
```suggestion
    expect(container.findByType(Text).props.children[0].props).toBeFalsy()
```

lets do this so its consistent with above?

2022-10-21 12:29 UTC, pvinis commented on src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tests.tsx
> +        expect(queryByText("5000$")).toBeNull()
```suggestion
        expect(queryByText("5000$")).toBeFalsy()
```
same

2022-10-21 12:29 UTC, pvinis commented on src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tests.tsx
> +    describe("For Confidential Notes", () => {
what about the rest of the toggles?

2022-10-21 13:19 UTC, rajsam003 commented on src/app/sharedUI/items/ArtworkGridItem.tests.tsx
> +    expect(container.findByType(Text).props.children[0].props).toBeTruthy()
It is actually the status dot. When I debug it renders as <Text/> component. I am not sure. Would be happy to pair on this with you.

2022-10-21 13:27 UTC, rajsam003 commented on src/app/sharedUI/screens/Artwork/Artwork.tsx
> +              isLastRow={isEditArtworkHidden}
No. Only the last row get this prop, to hide the line below below it

2022-10-21 13:33 UTC, rajsam003 commented on src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tests.tsx
> +    describe("For Confidential Notes", () => {
I wrote test for all toggles. Its in the tests file of components that are using it.

2022-10-21 14:36 UTC, pvinis approved these changes
awesome. we will pair on adding some last tests, and we can merge 👍

2022-10-21 14:44 UTC, gkartalis approved these changes

2022-10-21 15:42 UTC, pvinis commented
followup work, a PR to add a test for "edit in cms" button hiding.

2022-10-21 16:01 UTC, merged

2022-10-24 12:58 UTC, pvinis commented
ticket here https://artsyproduct.atlassian.net/browse/MOPLAT-474