feat: Search part 1
artsy/energy pull request #283
Opened 2022-10-24 13:01 UTC by rajsam003

This PR resolves [MOPLAT-422]

https://user-images.githubusercontent.com/17421923/197531103-8d816b50-c5f5-4828-a8b5-f3d390174c7e.mov

### PR Checklist

- [x] I tested my changes on **iOS** and **Android**.
- [x] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.

### To the reviewers 👀

- [x] I would like **at least one** of the reviewers to run this PR on the simulator or device.

Need help with something? Have a look at our [docs], or get in touch with us.

[docs]: /docs/README.md

2022-10-24 13:06 UTC, rajsam003 commented on src/palette/elements/Pill/Pill.tsx
> +export const Pill: React.FC<PillProps> = ({
@pvinis Do we have <Pill /> in artsy/palette-token ?

2022-10-24 13:44 UTC, rajsam003 commented on src/app/screens/HomeTabs/Search/SearchResult.tsx
> +export const SearchResult = ({ searchInput }: { searchInput: string }) => {
Had to add this, as SuspenseWrapper was not helping. It was loading the whole screen.

2022-10-25 09:21 UTC, pvinis commented on ios/Energy.xcodeproj/project.pbxproj
> +				"EXCLUDED_ARCHS[sdk=iphonesimulator*]" = "arm64 ";
it's not

2022-10-25 09:25 UTC, pvinis commented on src/palette/elements/Pill/Pill.tsx
> +export const Pill: React.FC<PillProps> = ({
it's not yet. you did good by adding it here. we can move it to palette-mobile soon

2022-10-25 09:27 UTC, pvinis reviewed
nice. I think only the Screen comment needs addressing, then it's ready

2022-10-25 09:27 UTC, pvinis commented on src/app/screens/HomeTabs/Search/Search.tsx
> +    <Flex flex={1} pt={insets.top} px={2} backgroundColor="background">
no more of that ;)

can you use Screen?

2022-10-25 09:27 UTC, pvinis commented on src/app/screens/HomeTabs/Search/SearchResult.tsx
> +export const SearchResult = ({ searchInput }: { searchInput: string }) => {
yep. that's what we were discussing the other day about having more local suspense wrappers.

2022-10-25 09:28 UTC, pvinis requested changes
wrong button before.

2022-10-25 09:42 UTC, rajsam003 commented on src/app/screens/HomeTabs/Search/Search.tsx
> +    <Flex flex={1} pt={insets.top} px={2} backgroundColor="background">
OOPS. Oh yess. haha

2022-10-25 16:19 UTC, pvinis commented on ios/Energy.xcodeproj/project.pbxproj
> +				"EXCLUDED_ARCHS[sdk=iphonesimulator*]" = "arm64 ";
you can revert this file.

also, here's a PR that should solve this git diff generation. https://github.com/artsy/energy/pull/285

2022-10-26 12:13 UTC, pvinis approved these changes
nice. one tiny comment and then feel free to merge, ill assign it back.

2022-10-26 12:13 UTC, pvinis commented on src/app/screens/HomeTabs/Search/Search.tsx
> +      <Screen.RawHeader>
heeeeeell yea!! nice, sam!

2022-10-26 12:13 UTC, pvinis commented on src/app/screens/HomeTabs/Search/Search.tsx
> +        <Separator />
i would move this to the header I think.

2022-10-26 12:17 UTC, rajsam003 commented on src/app/screens/HomeTabs/Search/Search.tsx
> +        <Separator />
Then we would need to wrap <Separator> and this existing header into <Flex> and give mx=2.
```
 <Screen.RawHeader>
      <Flex mx={2}>
        <Flex>//Header</Flex>
      </Flex>
      <Separator />
    </Screen.RawHeader>
```
Is that fine?

2022-10-26 14:14 UTC, merged