feat: Album document tab screen with new API
artsy/energy pull request #311
Opened 2022-11-09 13:05 UTC by rajsam003

This PR resolves [MOPLAT-480]

https://user-images.githubusercontent.com/17421923/200837896-42bbf12d-1a3d-496b-8dcd-270a1b4b759e.mov

### PR Checklist

- [x] I tested my changes on **iOS** and **Android**.
- [x] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.

### To the reviewers 👀

- [x] I would like **at least one** of the reviewers to run this PR on the simulator or device.

Need help with something? Have a look at our [docs], or get in touch with us.

[docs]: /docs/README.md

2022-11-09 15:56 UTC, dblandin approved these changes
Nice! 🥳

2022-11-09 15:56 UTC, dblandin commented on src/app/screens/HomeTabs/Albums/AlbumTabs/AlbumDocuments.tsx
> +            publicUrl
**suggestion**: Remember to use the preferred fields of `publicURL` and `filesize` here so we can remove the deprecated `size` and `publicUrl` fields soon. 👍🏼

2022-11-09 15:57 UTC, rajsam003 commented on src/app/screens/HomeTabs/Albums/AlbumTabs/AlbumDocuments.tsx
> +            publicUrl
Oh yes. I totally forgot. Thanks

2022-11-10 14:11 UTC, pvinis requested changes
nice. can we move the installs tab in the middle, so its consistent with the ShowTabs?

2022-11-10 14:19 UTC, pvinis approved these changes

2022-11-10 14:19 UTC, merged