fix : Artwork border box and About the artwork title should be hidden if artwork detail is empty
artsy/energy pull request #312
Opened 2022-11-09 14:48 UTC by rajsam003

This PR resolves [MOPLAT-495]

### PR Checklist

- [ ] I tested my changes on **iOS** and **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

Need help with something? Have a look at our [docs], or get in touch with us.

[docs]: /docs/README.md

2022-11-11 22:52 UTC, pvinis requested changes
not sure about this change.

2022-11-11 22:52 UTC, pvinis commented on src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
> -    internalDisplayPrice ||
this feels.. weird? why did it now show with that line? was it `""`?

also, would it show the box when there is only an internal display price now, or will we figure out the box is missing in that specific case? 🤔

2022-11-14 14:58 UTC, rajsam003 commented on src/app/sharedUI/screens/Artwork/ArtworkContent/ArtworkContent.tsx
> -    internalDisplayPrice ||
I basically just removed this from `shouldDisplayTheDetailBox` as we are not displaying the price inside that box. We are displaying `internalDisplayPrice ` and `price` above the box

2022-11-14 17:06 UTC, pvinis approved these changes

2022-11-14 17:06 UTC, merged