WIP:feat(moplat-233):shows
artsy/energy pull request #38
Opened 2022-05-20 14:01 UTC by patrinoua

This PR resolves []

### Description

### PR Checklist

- [ ] I tested my changes on **iOS** and **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

Need help with something? Have a look at our [docs], or get in touch with us.

[docs]: /docs/README.md

2022-05-24 16:59 UTC, patrinoua commented on src/Screens/HomeTabs/Shows/Shows.tsx
> +                  url
What is the right field here, url, imageURL? @pvinis any idea?

2022-05-24 17:00 UTC, rajsam003 commented on src/Screens/HomeTabs/Shows/Shows.tsx
> +    { partnerID }
Lets avoid adding @ts-ignore

```suggestion
    { partnerID: partnerID! }
```

2022-05-25 15:46 UTC, pvinis commented on src/Screens/HomeTabs/Shows/Shows.tsx
> +    graphql`
one thing we could do here is move that query in a variable below the component, so we keep the component code a tiny bit cleaner, like

```
export const Shows = () => {
  const partnerID = GlobalStore.useAppState((state) => state.activePartnerID)
  const data = useLazyLoadQuery<ShowsTabQuery>(showsQuery)
..
}

const showsQuery = graphql`
  query ShowsTabQuery
  ..
`
```

2022-05-25 15:47 UTC, pvinis commented on src/Screens/HomeTabs/Shows/Shows.tsx
> +                  url
not sure. i would check on eigen maybe, or ask in #dev-help 🤔.

2022-05-25 15:47 UTC, pvinis commented on src/Screens/HomeTabs/Shows/ShowsTabFlatList/ShowsTabFlatList.tsx
> +//remove any before merging
;)

2022-05-31 22:49 UTC, pvinis commented on src/Screens/HomeTabs/Shows/Shows.tsx
> +                  url
i think we figured this out right?

2022-05-31 22:50 UTC, pvinis commented on src/Screens/HomeTabs/Shows/ShowsTabFlatList/ShowsTabFlatList.tsx
> +export const ShowsTabFlatList = ({ shows }: { shows: any }) => {
do we need a component just to return the TabsFlatList? why not just using that directly in the Shows.tsx file? 🤔

2022-05-31 22:50 UTC, pvinis commented on src/Screens/HomeTabs/Shows/Shows.tests.tsx
> +    expect(queryAllByText("Gustav Klimts shows")).toHaveLength(10)
nice

2022-05-31 22:51 UTC, pvinis commented on src/Screens/HomeTabs/Shows/Shows.tsx
> +    graphql`
i think it makes sense to put the query outside the component in all cases. it seems a bit cleaner? but yea, lets talk tomorrow?

2022-05-31 22:52 UTC, pvinis requested changes
i left some comments. let me know what you think.

2022-06-01 13:01 UTC, patrinoua commented
replaced from https://github.com/artsy/energy/pull/48

2022-06-01 13:01 UTC, closed without merging