feat: with RetryErrorBoundary and fetchKeys
artsy/energy pull request #431
Opened 2023-01-04 11:45 UTC by rajsam003

This PR resolves [MOPLAT-541]

This PR adds the retry button in the error screen. The implementation is referred from https://relay.dev/docs/guided-tour/rendering/error-states/#when-using-uselazyloadquery

![image](https://user-images.githubusercontent.com/17421923/210548129-22c10291-a9af-4fa7-b16c-b43c52aaa2e2.png)

### Description

### PR Checklist

- [x] I tested my changes on **iOS** and **Android**.
- [x] I added screenshots or videos to illustrate my changes.
- [x] I added Tests and Stories for my changes.

### To the reviewers 👀

- [x] I would like **at least one** of the reviewers to run this PR on the simulator or device.

Need help with something? Have a look at our [docs], or get in touch with us.

[docs]: /docs/README.md

2023-01-04 16:13 UTC, damassi commented on src/app/components/GlobalErrorView.tsx
> +      <Text>Error: {error?.message}</Text>
Ditto about palette

2023-01-04 16:14 UTC, damassi commented on src/app/components/Items/AlbumListImage.tsx
> +export const AlbumListImage = ({ slug, style, fetchKey }: AlbumListImageProps) => {
As mentioned in slack, we shouldn't have to pass fetch key's all around the app. They can be stored in global state and then managed within the `useSystemQueryLoader` (with these `useLazyLoadQueries` being replaced.

2023-01-04 16:16 UTC, damassi commented on src/app/components/LoadFailureView.tsx
> +export const LoadFailureView: React.FC<LoadFailureViewProps & BoxProps> = ({
Since this is ultimately tied to an `ErrorBoundary`, we should keep the language the same: `LoadErrorView` (vs mixing "failure" and "error").

2023-01-04 16:27 UTC, damassi requested changes
I think we can make this approach simpler and less brittle! Happy to work through the implementation together and brainstorm.

In general, it's the sort of thing where anytime we're doing something numerous times its good to step back and ask: can we automate this? Can we make it transparent so that future devs don't need to add additional wiring to create new views? Because every time a new API addition like this gets added, it creates another thing that we need to worry about and refactor should something change underneath.

2023-01-05 10:15 UTC, rajsam003 commented on src/app/components/GlobalErrorView.tsx
> +    <View style={{ flex: 1, justifyContent: "center", alignItems: "center" }}>
We have wrapped all the providers with `<GlobalRetryErrorBoundary>`. ThemeProvider is one of them, which provides theme for palette component `<Text>`.
As `<GlobalErrorView>` is the child component of `<GlobalRetryErrorBoundary>`. We cannot use `<Text>` from palette in it.  I've used `<Text>` from `react-native` lib. Also <Flex>. Just to import both from the same library.

2023-01-05 10:19 UTC, rajsam003 commented on src/app/components/GlobalErrorView.tsx
> +      <Text>Error: {error?.message}</Text>
addressed the reason in the above comment.

2023-01-05 10:21 UTC, rajsam003 commented on src/app/components/Items/AlbumListImage.tsx
> +export const AlbumListImage = ({ slug, style, fetchKey }: AlbumListImageProps) => {
Good idea. Can we share the same global fetchKey to all the queries? Just wondering.

2023-01-05 10:28 UTC, rajsam003 commented
> I think we can make this approach simpler and less brittle! Happy to work through the implementation together and brainstorm. See [this slack thread](https://artsy.slack.com/archives/C02NAJ2CGLW/p1672857367275759) for a possible approach.
> 
> In general, it's the sort of thing where anytime we're doing something numerous times its good to step back and ask: can we automate this? Can we make it transparent so that future devs don't need to add additional wiring to create new views? Because every time a new API addition like this gets added, it creates another thing that we need to worry about and refactor should something change underneath.

Thanks @damassi :). I totally agree. We should always try to automate code to make it easier for future devs.

2023-01-05 16:51 UTC, damassi commented on src/app/components/GlobalErrorView.tsx
> +    <View style={{ flex: 1, justifyContent: "center", alignItems: "center" }}>
@rajsam003 - any chance this error boundary can go _after_ `<Theme>`, or move `<Theme>` to the top?

2023-01-05 16:51 UTC, damassi commented on src/app/components/GlobalErrorView.tsx
> +      <Text>Error: {error?.message}</Text>
https://github.com/artsy/energy/pull/431#discussion_r1062684783

2023-01-05 16:54 UTC, damassi commented on src/app/components/Tabs/TabsScreenWrapper.tsx
> +export const TabsScreenWrapper: React.FC = ({ children }) => {
We can probably simplify the name! No need to add `Wrapper`. 

```
<TabScreen>
  ...
</TabScreen>
```

feels nice and clean

2023-01-05 16:57 UTC, damassi approved these changes
Looks great @rajsam003 -- Thanks for working through those updates 👍 

One suggestion about updating the naming of that one component to just `<TabScreen>` but otherwise LGTM

2023-01-06 16:26 UTC, merged

2023-01-07 11:32 UTC, pvinis commented on src/app/components/GlobalErrorView.tsx
> +    <View style={{ flex: 1, justifyContent: "center", alignItems: "center" }}>
it could