feat: Artwork screen
artsy/energy pull request #53
Opened 2022-06-03 14:32 UTC by rajsam003

This PR resolves [MOPLAT-257]

### Description

https://user-images.githubusercontent.com/17421923/171874696-979a2603-c354-418f-a4da-dccb9c2ad310.mov

### PR Checklist

- [ ] I tested my changes on **iOS** and **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

Need help with something? Have a look at our [docs], or get in touch with us.

[docs]: /docs/README.md

[MOPLAT-257]: https://artsyproduct.atlassian.net/browse/MOPLAT-257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2022-06-04 09:19 UTC, pvinis approved these changes
great work! maybe we can remove the unused mock thing, and then feel free to merge 👍

2022-06-04 09:19 UTC, pvinis commented on src/Screens/_shared/ArtworkGridItem.tsx
> +          slug: artwork.slug || "",
not blocking, but I wonder if this is not a good practice. if the slug is null, then passing empty string will just cause the next screen to freak out. I wonder if making the touchable not tappable is better? 🤔

also, if we know the slug is there, we could use a !. otherwise I guess the current screen would probably have issues displaying the artwork.

I also wonder if on MP we should make the slug not nullable, because is it ever null?

2022-06-04 09:19 UTC, pvinis commented on src/shared/tests/getEssentialProps.tsx
> +export const getEssentialProps = (params: {} = {}) =>
what is this? i don't see this used anywhere 🤔. also, if it is, maybe we turn this into a mock?

2022-06-04 09:19 UTC, pvinis commented on src/Screens/_shared/Artwork/Artwork.tsx
> +    <Suspense
not for this PR, but now that we see this pattern everywhere, it might be worth giving some time to it to extract it in a comp and reuse it.

something like ArtsySuspense (or a better name 😅) that has the wraps children in a suspense with the fallback defaulting to the activityindicator 🤔

2022-06-05 08:23 UTC, pvinis commented on src/Screens/_shared/ArtworkGridItem.tsx
> +          slug: artwork.slug || "",
as Damon says here https://artsy.slack.com/archives/C2TQ4PT8R/p1654364617093749?thread_ts=1654334440.295129&channel=C2TQ4PT8R&message_ts=1654364617.093749 slug is already non null. and I see it too in the gql files in this PR. so let's just remove the || "" part.

2022-06-05 08:24 UTC, pvinis requested changes
added one more comment for the slug

2022-06-06 07:38 UTC, rajsam003 commented on src/Screens/_shared/Artwork/Artwork.tests.tsx
> +    const { queryByText } = renderWithWrappersTL(<Artwork {...getEssentialProps()} />)
here @pvinis

2022-06-06 07:39 UTC, rajsam003 commented on src/shared/tests/getEssentialProps.tsx
> +export const getEssentialProps = (params: {} = {}) =>
Its is used [here](https://github.com/artsy/energy/pull/53/files#r889898645). To get navigation and route as props

2022-06-06 07:42 UTC, rajsam003 commented on src/Screens/_shared/Artwork/Artwork.tsx
> +    <Suspense
Sure. I was thinking about it too.

2022-06-08 14:40 UTC, pvinis approved these changes

2022-06-09 08:52 UTC, merged