refactor(select-mode): Refactor select mode app-wide, including album management
artsy/energy pull request #536
Opened 2023-03-01 00:38 UTC by damassi

### Description

WIP

### PR Checklist

- [ ] I have tested my changes on **iOS** and **Android**.
- [ ] I have included **screenshots** or **videos**, or I have not changed the UI.
- [ ] I have added **tests**, or my changes don't require any.
- [ ] I added an **[app state migration]**, or my changes do not require one.
- [ ] I have documented any **follow-up work** that this PR will require, or it does not require any.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

2023-03-01 00:39 UTC, damassi commented on src/app/screens/Albums/navigation.tsx
> +    slug: string
note to self: should this slug be artwork

2023-03-01 06:03 UTC, ArtsyOpenSource commented
<!--
  0 failure: 
  1 warning:  It looks like you...
  
  
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  It looks like you've modified a store model. If necessary, please be sure to add a migration to `migrations.ts`. See the [migration-docs](https://github.com/artsy/eigen/blob/main/docs/adding_state_migrations.md) for more info.
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 3f12dbb2b6e45222d79e9067f2195130e72ce16d
</p>

2023-03-01 07:04 UTC, damassi commented on src/app/components/BottomSheetModalView.tsx
> +            height="50px"
When we see unit warnings in Folio / Eigen, this is what it is. Update with `px` and it should fix

2023-03-01 07:07 UTC, damassi commented on src/app/screens/Albums/AddItemsToAlbum.tsx
> +  const { closeBottomSheetModal, artworkToAdd } = useRoute<HomeTabsRoute>().params
First key bit to note as it applies throughout. We're no longer passing IDs around, but rather the node which now includes a `__typename` field on the query so that we can disambiguate between Artwork, InstallShots and Documents. 

No need to have separate categories in the app when our GraphQL schema describes these things already.

2023-03-01 07:08 UTC, damassi commented on src/app/screens/Albums/AddItemsToAlbum.tsx
> -    (state) => state.selectMode.sessionState.documents
Example of how this simplifies. No more separate state categories that need to be managed. We now just select whatever in select mode; its a single thing

2023-03-01 07:09 UTC, damassi commented on src/app/screens/Albums/AddItemsToAlbum.tsx
> +    (state) => state.selectMode.sessionState.selectedItems
Selected items are all under this state slice now, and in every screen we can leverage no matter what the item type.

2023-03-01 07:09 UTC, damassi commented on src/app/screens/Albums/AlbumTabs/AlbumArtworks.tsx
> +            }}
TODO: This fixes a JIRA bug, need to track down ticket

2023-03-01 07:10 UTC, damassi commented on src/app/screens/Albums/AlbumTabs/AlbumArtworks.tsx
> +            ...Artwork_artworkProps @relay(mask: false)
For any artworks that we have in the app, no need to define duplicate fields everywhere, and instead just spread in this unmasked fragment.

2023-03-01 07:11 UTC, damassi commented on src/app/screens/Albums/AlbumTabs/AlbumDocuments.tsx
> +        contentContainerStyle={getContentContainerStyle(documents)}
Removed lots of duplication around container styling here

2023-03-01 07:13 UTC, damassi commented on src/app/screens/Albums/AlbumTabs/AlbumTabs.tsx
> +const getAlbumIds = (items: SelectedItem[]) => {
Returns various relevant IDs for rendering items in album tabs. Note how we're leaning on `__typename`, which allowed us to remove a lot of state in the app

2023-03-01 07:15 UTC, damassi commented on src/app/screens/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
> -                selectedToRemove={selectedArtworksToRemove.includes(artwork.internalID)}
No need to rely on local state, since we can evaluate global selectMode state and share it

2023-03-01 07:16 UTC, damassi commented on src/app/screens/Albums/CreateOrEditAlbum/CreateOrEditAlbumChooseArtworks.tsx
> +      artworksToAdd: selectedItems,
Another notable thing is we can pass data around our router. So rather than posting data to the global store about what items will be added / removed, we can simply pass it along via the router to the next screen.

2023-03-01 07:19 UTC, damassi commented on src/app/screens/Albums/CreateOrEditAlbum/CreateOrEditAlbumChooseArtworks.tsx
> -  const selectedArtworks = useArtworksByMode(mode, slug)
We no longer need to manage concepts of "mode", since we're just leveraging global selected item state. Don't need to know anything more than there being a screen that contains items, if they're selected we use them

2023-03-01 07:19 UTC, damassi commented on src/app/screens/Artists/ArtistTabs/ArtistArtworks/ArtistArtworks.tsx
> +    GlobalStore.actions.selectMode.toggleSelectedItem(artwork)
This is how we mark items selected or deselected, via this action

2023-03-01 07:21 UTC, damassi commented on src/app/screens/Artists/ArtistTabs/ArtistDocuments/ArtistDocuments.tsx
> +    GlobalStore.actions.selectMode.toggleSelectedItem(doc)
Same thing here -- a document is diambiguated by evaluating `__typename` lower down.

2023-03-01 07:22 UTC, damassi commented on src/app/screens/Artists/ArtistTabs/ArtistTabs.tsx
> +  const { sendMail } = useMailComposer()
Note that our emailer _also_ taps into our shared global select mode state, so no need to pass anything to it, just use the hook and fire `sendMail` after items are selected

2023-03-01 07:24 UTC, damassi commented on src/app/screens/Artwork/useMailComposer.ts
> +        console.log(bodyHTML)
todo: remove

2023-03-01 07:25 UTC, damassi commented on src/app/screens/Artwork/useMailComposer.ts
> +export function getArtworkEmailSnippet(artwork: ArtworkEmailSnippetProps, fullHtml = true) {
todo: rename `getArtworkEmailTemplate`

2023-03-01 07:26 UTC, damassi commented on src/app/screens/Shows/ShowTabs/ShowDocuments/ShowDocuments.tsx
> +            GlobalStore.actions.selectMode.setSelectedItems([])
todo: `setSelectedItems` -> `selectItems`, also `clearSelectedItems`

2023-03-01 07:27 UTC, damassi commented on src/app/system/store/Models/AlbumsModel.tests.tsx
> -          .selectedArtworksForExistingAlbum
These test cases are no longer necessary

2023-03-01 07:28 UTC, damassi commented on src/app/system/store/Models/AlbumsModel.ts
> -  clearSelectedArtworksForEditAlbum: Action<this>
All of these actions have been collapsed into just `addToAlbum` and `removeFromAlbum`

2023-03-01 07:29 UTC, damassi commented on src/app/system/store/Models/AlbumsModel.ts
> +  // TODO: listen for this and deselect
todo: remove this comment

2023-03-01 07:31 UTC, damassi commented on src/app/system/store/Models/SelectModeModel.ts
> +    }
Easy-peasy listeners are extremely handy. When such and such actions fire, perform some other thing. So here, when we add an item, add an album or edit, we just exit select mode and clear out any currently selected items for the next session.

2023-03-01 07:32 UTC, damassi commented on src/app/system/store/Models/SelectModeModel.ts
> +  | NonNullable<NonNullable<NonNullable<ShowInstallsQuery$data["show"]>["images"]>[0]>
These types are unfortunate, but there's nothing we can do to simplify it further without some TypeScript magic. 

If we were ever to add additional asset times to be saved to a collection, we could add the query type here and it should "just work"

2023-03-01 07:33 UTC, damassi commented on src/app/system/store/Models/SelectModeModel.ts
> +export type SelectedItemDocument = Extract<SelectedItem, { __typename: "Document" }>
TypeScript's `Extract` utility type is how you disambiguate union types. Its super cool!

2023-03-01 07:35 UTC, damassi commented on src/app/system/sync/syncManager.ts
> -  }
Was able to remove some queries from the offline sync with this work. 

Since we're storing the full response object in the album now we can likely eliminate a few more queries on the app (which should fix some of the suspense loading when transitioning between album screens). Will look into that tomorrow.

2023-03-01 07:36 UTC, damassi commented on src/app/utils/getContentContainerStyle.ts
> +    paddingHorizontal: items.length ? 0 : 20,
We nave no way to access our spacing scale outside of a `useSpace` hook, which is impractical in certain contexts. Need to add that to palette-mobile

2023-03-01 11:03 UTC, MounirDhahri approved these changes
Nice PR!

2023-03-01 13:38 UTC, gkartalis approved these changes
nice one

2023-03-01 13:38 UTC, gkartalis commented on src/app/screens/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
> +          const items = differenceBy(artworksToSave, selectedItems, "internalID")
nice one! never used it before but looks super useful

2023-03-01 13:38 UTC, gkartalis commented on src/app/screens/Artists/ArtistTabs/ArtistTabs.tsx
> +              onPress={shareByEmailHandler}
wow, so much cleaner 🌟 🧹

2023-03-01 13:38 UTC, gkartalis commented on src/app/screens/Shows/ShowTabs/ShowDocuments/ShowDocuments.tsx
> +            __typename
**question:** do we actually use this anywhere? 👀

2023-03-01 13:38 UTC, gkartalis commented on src/app/system/store/Models/SelectModeModel.ts
> +  | NonNullable<NonNullable<NonNullable<ShowInstallsQuery$data["show"]>["images"]>[0]>
😅

2023-03-01 13:38 UTC, gkartalis commented on src/app/system/store/Models/SelectModeModel.ts
> +export type SelectedItemDocument = Extract<SelectedItem, { __typename: "Document" }>
super useful ++++ thanks!

2023-03-01 13:38 UTC, gkartalis commented on src/app/system/store/Models/SelectModeModel.ts
> +export type SelectedItemDocument = Extract<SelectedItem, { __typename: "Document" }>
oh, maybe that's why you added the `__typename` in some places ([here ](https://github.com/artsy/energy/pull/536/files#diff-103e6df4fe033078fd013e446459826529e46c8e213ee01237185d8999537b9eR74)is one example)

2023-03-01 13:38 UTC, gkartalis commented on src/app/system/sync/syncManager.ts
> -  }
in case you can't do that there is this helpful relay [doc](https://relay.dev/docs/guided-tour/refetching/refetching-queries-with-different-data/) on how to avoid suspense

2023-03-01 15:02 UTC, brainbicycle commented on src/app/components/Items/AlbumListImage.tsx
> +        GlobalStore.actions.albums.removeItemFromAlbums(slug)
is this the reason I am not seeing them removed?

2023-03-01 15:23 UTC, brainbicycle requested changes
This is looking much simpler! 🙌 

I see a couple bugs when running locally:
1. Native albums are no longer rendering images
2. Getting a type error when adding artworks from select mode on an artist page to an album
3. When creating a new album instead of landing on the albums tab I am landing on the artist page

(I'll put more specifics in slack)

2023-03-01 16:44 UTC, damassi commented on src/app/components/BottomSheetModalView.tsx
> +            height="50px"
Honestly didn't look, but I don't think so. styled-system can accept any kind of value like this under the hood

2023-03-01 17:33 UTC, damassi commented on src/app/components/Items/AlbumListItem.tsx
> +          if (!item) return null
I think in this case I was trying to make the type-checker happy; this whole component should exit early if there are no items (will fix)

2023-03-01 17:39 UTC, damassi commented on src/app/screens/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
> +                  !!selectedItems.find((item) => item?.internalID === artwork.internalID)
I wanna go through and clean up all of these existy checks... lodash could again simplify: 
```tsx
findBy(selectedItems, { internalID: artwork.internalID }) 
```

2023-03-01 17:43 UTC, damassi commented on src/app/screens/Artwork/useMailComposer.ts
> +          console.log("[useMailComposer] Error sending email:", error)
Oh good idea, will do 👍

2023-03-01 17:45 UTC, damassi commented on src/app/screens/Shows/ShowTabs/ShowDocuments/ShowDocuments.tsx
> +            __typename
Yup, down below

2023-03-02 07:41 UTC, damassi commented
Alright @brainbicycle - this is ready to go 👍

2023-03-02 07:46 UTC, damassi commented on src/app/components/BottomSheetModalView.tsx
> +              opacity: 0.0,
Removed the dark opacity for now because the way it clonks in is super janky. Added a shadow on the bottom sheet per other ticket, looks wayy better

2023-03-02 07:47 UTC, damassi commented on src/app/components/BottomSheetModalView.tsx
> +    activeOpacity={0.5}
Fixes issue around selection being invisible per jira ticket

2023-03-02 07:47 UTC, damassi commented on src/app/components/Items/AlbumListImage.tsx
> +        GlobalStore.actions.albums.removeItemFromAlbums(slug)
Will return to the other ticket after this and verify, have a note about it

2023-03-02 07:48 UTC, damassi commented on src/app/components/__tests__/SelectMode.tests.tsx
> +})
Most of this file was written by ChatGPT ❇️

2023-03-02 17:57 UTC, merged