feat: Persist albums
artsy/energy pull request #64
Opened 2022-06-15 13:28 UTC by rajsam003

This PR resolves [MOPLAT-300]

### Description

To enable creation, editing, and deletion of albums in GlobalStore and to wire up with `Create Album` button to use the storage

### PR Checklist

- [x] I tested my changes on **iOS** and **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

Need help with something? Have a look at our [docs], or get in touch with us.

[docs]: /docs/README.md

[MOPLAT-300]: https://artsyproduct.atlassian.net/browse/MOPLAT-300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2022-06-15 13:52 UTC, patrinoua commented on package.json
> +    "moment": "^2.29.3",
Good catch. Do we have a broadly used preferred alternative? [Luxon](https://moment.github.io/luxon/) [Day.js](https://day.js.org/) [date-fns](https://date-fns.org/) [js-Joda](https://js-joda.github.io/js-joda/) [Date](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Date) object ?

2022-06-15 13:53 UTC, pvinis commented on package.json
> +    "moment": "^2.29.3",
we have luxon already. lets use that.

2022-06-15 13:56 UTC, pvinis commented on package.json
> +    "react-native-uuid": "^2.0.1",
not blocking, but i recently found out about https://github.com/ulid/spec, which is i think the same as uuid v7. if we wanna be the cool kids, we could totally use https://github.com/ulid/javascript. but again, not blocking

2022-06-15 13:58 UTC, pvinis commented on src/app/store/Models/AlbumsModel.ts
> +  artworkIds?: string[]
we can remove the `?` already. a new album with no artworks will just have `[]` here.

2022-06-15 13:59 UTC, MounirDhahri requested changes

2022-06-15 13:59 UTC, MounirDhahri commented on src/app/screens/HomeTabs/Albums/CreateAlbum.tsx
> +import moment from "moment"
**thought:** is there a particular reason why you would like to use `moment` here? maybe you can do the same using `luxon`

2022-06-15 13:59 UTC, MounirDhahri commented on src/app/screens/HomeTabs/Albums/CreateAlbum.tsx
> +          title: values.albumName,
**suggestion:**
```suggestion
          title: values.albumName.trim(),
```

2022-06-15 13:59 UTC, MounirDhahri commented on src/app/screens/HomeTabs/Albums/CreateAlbum.tsx
> +    useFormik<CreateAlbumValuesSchema>({
**thought:** I am not sure you need `useFormik` here, maybe `useFormikContext` instead 👀

2022-06-15 13:59 UTC, MounirDhahri commented on src/app/screens/HomeTabs/Albums/CreateAlbum.tsx
> +          createdAt: moment().format(),
**suggestion:** I would suggest storing the ISO date and then formatting it when needed instead.

2022-06-15 13:59 UTC, MounirDhahri commented on src/app/screens/HomeTabs/Albums/CreateAlbum.tsx
> +        navigation.navigate("HomeTabs")
**issue:** this will navigate to `HomeTabs` anyway even if `AddAlbum` fails right? maybe we can adjust the action to tell if it failed or not and only navigate back to home when we successfully add an album

2022-06-15 13:59 UTC, MounirDhahri commented on src/app/screens/HomeTabs/Albums/CreateAlbum.tsx
> +              defaultValue={values.albumName}
interesting use here - i was expecting value

2022-06-15 13:59 UTC, MounirDhahri commented on src/app/store/Models/AlbumsModel.ts
> +  artworkIds?: string[]
I don't agree with having `?` here, an empty array makes more sense to me

2022-06-15 14:05 UTC, rajsam003 commented on package.json
> +    "react-native-uuid": "^2.0.1",
Looks good. 
`ulid` is more popular than `react-native-uuid`
but `react-native-uuid` has only 1 open issue. 
Now I am confused which one to use. 😂

2022-06-15 14:38 UTC, MounirDhahri commented on src/app/screens/HomeTabs/Albums/CreateAlbum.tsx
> +        navigation.navigate("HomeTabs")
yes, something like that would be fine - the `goBack()` doesn't make much sense to me though

2022-06-15 14:40 UTC, pvinis commented on package.json
> +    "react-native-uuid": "^2.0.1",
go with the one you have added already 👍

2022-06-15 15:10 UTC, rajsam003 commented on src/app/store/Models/AlbumsModel.ts
> +  updateAlbum: action((state, album) => {
If we do that then I am worried if the updated artwork is at the top or the middle will come to the bottom of the list. 
And in this case, I don't mind passing the whole album as it would have only array of `ids`.
What do you think? If you still think it's not a good idea, I can change it :)

2022-06-15 15:17 UTC, rajsam003 commented on src/app/screens/HomeTabs/Albums/CreateAlbum.tsx
> +          })
@MounirDhahri As you can see I have used `CommonActions` to reset stack navigator. It works really good but it takes the screen to the first tab of the home screen whereas the Album belongs to the third tab. Do you know how to solve this?

2022-06-15 18:36 UTC, pvinis commented on src/app/store/Models/AlbumsModel.ts
> +  updateAlbum: action((state, album) => {
i think we should definitely sort them in the list view, so we shuold not care where they are in the array here. either we sort in the view, or we sort in the model, but we sort somewhere, rather than hope we put it in the right place accidentally.

what about this, we keep it as is, and when we do the artwork screens, we can see how it might work best?

2022-06-16 09:44 UTC, rajsam003 commented on src/app/store/Models/AlbumsModel.ts
> +  updateAlbum: action((state, album) => {
Sure. Sounds good

2022-06-16 10:27 UTC, rajsam003 commented on src/app/screens/HomeTabs/Albums/CreateAlbum.tsx
> +          })
I think I can solve this using forwardRef

2022-06-17 08:18 UTC, merged