feat: Create album button adjustment
artsy/energy pull request #65
Opened 2022-06-17 12:17 UTC by rajsam003

This PR resolves []

### Description

### PR Checklist

- [ ] I tested my changes on **iOS** and **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

Need help with something? Have a look at our [docs], or get in touch with us.

[docs]: /docs/README.md

2022-06-21 11:19 UTC, rajsam003 commented on src/app/screens/HomeTabs/Albums/CreateAlbum.tsx
> +            artworkIds: ["5c8190cf1a61c940f01c7b9f", "5565cd02726169267c7e1300"], // mock data
Using mock data for now. We'll use the proper data with PR. 
We'll be working with proper data on PR. [Here](https://artsyproduct.atlassian.net/browse/MOPLAT-283) is the ticket

2022-06-21 11:29 UTC, rajsam003 commented on src/app/screens/HomeTabs/HomeTabs.tsx
> +      ) : null}
We cannot add `Create Album` button inside `Albums` screen as it should be wrapped with `TabsScrollView` and then the button is not sticking to the bottom of the screen
I also tried adding it outside the `TabsScrollView` in the Album component and use `position:"absolute"`. Then the whole screen goes blank. 
It is a wierd behaviour of [react-native-collapsible-tab-view](https://github.com/PedroBern/react-native-collapsible-tab-view#tabsscrollview)

2022-06-21 11:33 UTC, rajsam003 commented on src/app/screens/HomeTabs/HomeTabs.tsx
> +      ) : null}
This is a workaround I used using `useFocuseTab()` hook due to the following reason. 

We cannot add `Create Album` button inside `Albums` screen as it should be wrapped with `TabsScrollView` and then the button is not sticking to the bottom of the screen
I also tried adding it outside the `TabsScrollView` in the Album component and use `position:"absolute"`. 

`<><TabsScrollView>
scrollable...
</TabsScrollView>
<CreateAlbumButton position:"absolute" />
</>`

Then the whole screen goes blank. 
It is a wierd behaviour of [react-native-collapsible-tab-view](https://github.com/PedroBern/react-native-collapsible-tab-view#tabsscrollview)

2022-06-21 11:38 UTC, rajsam003 commented on src/app/screens/HomeTabs/Albums/Albums.tsx
> +            <AlbumListImage slug={album.artworkIds[0]} key={album.artworkIds[0]} />
For now, I am showing only the first artwork image. Rendering multiple images will be worked on other PR of [visualization of album ticket](https://artsyproduct.atlassian.net/browse/MOPLAT-285)

2022-06-22 07:51 UTC, pvinis requested changes

2022-06-22 07:51 UTC, pvinis commented on src/app/screens/HomeTabs/Albums/Albums.tsx
> +interface AlbumsProp {
prop or props?

2022-06-22 07:51 UTC, pvinis commented on src/app/screens/HomeTabs/Albums/Albums.tsx
> +  }, [focusedTab])
but where is it used? I don't see it used?

2022-06-22 07:51 UTC, pvinis commented on src/app/screens/HomeTabs/HomeTabs.tsx
> +      {focusedTab === "Albums" ? (
oh I see. I don't think this should be here. why should this be part of this file and not the albums screen?

2022-06-22 07:51 UTC, pvinis commented on src/app/screens/HomeTabs/HomeTabs.tsx
> +      ) : null}
hmmmm interesting.

I find this really confusing, I don't think this is a good pattern. maybe we can try and see what else we can think of to move that button on the albums screen rather than here? lets pair if you want.

2022-06-22 07:54 UTC, rajsam003 commented on src/app/screens/HomeTabs/HomeTabs.tsx
> +      ) : null}
Ya sure 👍🏽

2022-06-22 09:58 UTC, rajsam003 commented on src/app/screens/HomeTabs/Albums/Albums.tsx
> +        pb={safeAreaInsets.bottom}
Brilliant 💡

2022-06-22 09:59 UTC, rajsam003 commented on src/app/screens/HomeTabs/Albums/Albums.tsx
> +        pb={safeAreaInsets.bottom}
I didnt know this

2022-06-22 10:01 UTC, pvinis approved these changes

2022-06-22 10:11 UTC, merged