Rajsam003/moplat 304/edit album
artsy/energy pull request #92
Opened 2022-07-12 12:55 UTC by rajsam003

This PR resolves []

### Description

### PR Checklist

- [ ] I tested my changes on **iOS** and **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

Need help with something? Have a look at our [docs], or get in touch with us.

[docs]: /docs/README.md

2022-07-13 10:33 UTC, rajsam003 commented
> oh god, 10 files diff for changing the title 😱

No. hahaha.
Thats just one video

2022-07-13 10:36 UTC, pvinis commented on src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
> +    mode: "create",
feels like theres a lot of places we change the code flow based on the mode. why not keep these as separate components/screens? whats the benefit of all in one with many forks?

as a side idea, what if we break these down to smaller pieces, maybe some common ones and some not, so each screen can have some deduplicated stuff?

2022-07-13 10:36 UTC, pvinis commented on src/app/store/Models/AlbumsModel.ts
> -import _ from "lodash"
nice

2022-07-13 10:36 UTC, pvinis commented on src/app/store/Models/AlbumsModel.ts
> +    const index = state.albums.findIndex((x) => x.id === albumId)
just a random thought, i wonder if we should have made `albums` an object instead of an array 🤔

2022-07-13 17:21 UTC, dimatretyak commented on src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
> +              createdAt: DateTime.now().toISO(),
**suggestion**: what do you think about not passing the `id` and `createdAt` fields explicitly for the `addAlbum` action, but automatically assigning/adding these values [here](https://github.com/artsy/energy/blob/23dbf85d99491ce86bb7caa28b4cf28d88f32f81/src/app/store/Models/AlbumsModel.ts#L46-L48)?

For example, like this
```javascript
await GlobalStore.actions.albums.addAlbum({
  title: values.albumName.trim(),
  artworkIds: selectedArtworks,
})

...

addAlbum: action((state, album) => {
  const id = uuid.v4().toString()
  const createdAt = DateTime.now().toISO()
  
  state.albums.push({
    id,
    createdAt,
    ...album,
  })
})
```

2022-07-13 17:21 UTC, dimatretyak commented on src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbumChooseArtworks.tsx
> +      : GlobalStore.useAppState((state) => state.albums.sessionState.selectedArtworksForCreateAlbum)
**question**: maybe we can put this logic in a separate selector or custom hook and return artworks depending on passed mode? 

**Custom selector**
```javascript
const selectedArtworksInModel = GlobalStore.useAppState(getArtworksByMode(mode, albumId))
```

or 

**Custom hook (if it can be done)**
```javascript
const useArtworksByMode = (mode, albumId) => { ... }
const selectedArtworksInModel = useArtworksByMode(mode, albumId)
 
```

2022-07-13 17:29 UTC, dimatretyak commented on src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
> +          setLoading(true)
**suggestion**: I think here we should set `loading` flag to `false`

2022-07-13 17:31 UTC, dimatretyak commented on src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
> +          setLoading(true)
or maybe it's better to use `isSubmitting` from [Formik](https://formik.org/docs/api/formik#issubmitting-boolean)

2022-07-14 10:00 UTC, rajsam003 commented on src/app/screens/HomeTabs/Albums/AlbumArtworks.tsx
> +          marginTop: 20,
Should we?

2022-07-14 10:00 UTC, rajsam003 commented on src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
> +            await GlobalStore.actions.albums.clearAllSelectedArtworksForAnExistingAlbum(albumId)
Good idea, I will try that

2022-07-14 10:01 UTC, dimatretyak commented on src/app/screens/HomeTabs/Albums/AlbumArtworks.tsx
> +          marginTop: 20,
to tell the truth, I don't know for sure, and that's why I clarified this point with you 😅

2022-07-14 10:01 UTC, dimatretyak commented on src/app/screens/HomeTabs/Albums/AlbumArtworks.tsx
> +          marginTop: 20,
If not, then you can ignore the comment

2022-07-14 10:01 UTC, dimatretyak commented on src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
> +            await GlobalStore.actions.albums.clearAllSelectedArtworksForAnExistingAlbum(albumId)
Thanks!

2022-07-14 10:45 UTC, admbtlr commented on src/app/screens/HomeTabs/Albums/AlbumArtworks.tsx
> +          marginTop: 20,
:ceiling-cat: Yes, please do! Right now these are magic numbers, which is not great. And it's not crazy to imagine that we might want to increase spacing on tablets, for example

2022-07-14 15:29 UTC, rajsam003 commented on src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
> +    mode: "create",
As discussed, there will be a lot of code duplications if we split. so we are keeping it as it is

2022-07-14 15:32 UTC, rajsam003 commented on src/app/screens/HomeTabs/Albums/AlbumArtworks.tsx
> +          marginTop: 20,
In that case, there are a lot of places where we need to change. I will work on it in different PR.

2022-07-15 10:09 UTC, rajsam003 commented on src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
> +  const selectedArtworksInModel = useArtworksByMode(mode)
@dimatretyak I used custom hook as you advised☝️

2022-07-15 12:29 UTC, dimatretyak approved these changes
Good work👌
Left some comments and suggestions, but feel free to ignore them if you don't agree with them

2022-07-15 12:29 UTC, dimatretyak commented on src/app/store/Models/AlbumsModel.ts
> +
**suggestions** and **thoughts**: I agree with [this comment](https://github.com/artsy/energy/pull/92#discussion_r919926094) from Pavlos. It may be more convenient to store the data in a normalized state (something [like this](https://redux.js.org/tutorials/essentials/part-6-performance-normalization#normalized-state-structure)).

These are optional changes, just suggestions 😅

2022-07-15 12:29 UTC, dimatretyak commented on src/app/store/Models/AlbumsModel.ts
> +  selectArtworksForAnExistingAlbum: Action<this, Artworks | null>
**nitpick**: maybe use just `selectArtworksForNewAlbum` and `selectArtworksForExistingAlbum` (without **A** and **An**). Feel free to ignore this comment If you do not agree with it

2022-07-15 12:29 UTC, dimatretyak commented on src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
> +        backButtonAction={backButtonAction}
as far as I understand, this logic will not work if the user returns to the previous page using swipe back gesture or hardware back button on Android

2022-07-15 12:29 UTC, dimatretyak commented on src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
> +        albumName: mode === "edit" ? album?.name || "" : "",
**suggestion**: `album?.name ?? ""`

2022-07-15 12:36 UTC, pvinis commented on src/app/store/Models/AlbumsModel.ts
> +    if (index !== -1) {
i agree. lets do this @rajsam003, something like:
```
if (index === -1) {
  throw new Error("album not found") // or something
}
.. rest of the code as you have it, with state.ablums[index].name = name etc
```

2022-07-15 12:37 UTC, pvinis commented on src/app/store/Models/AlbumsModel.ts
> +    if (artistIndex !== -1) {
to @dimatretyak's point, this code here would be simpler if we turned this array into an object. but maybe we can do that when we touch that code next time, when we merge the add and delete components.

2022-07-15 12:40 UTC, pvinis commented on src/app/hooks/useArtworksByMode.tsx
> +export const useArtworksByMode = (mode: "create" | "edit", slug?: string) => {
i dont like this hook here. this is such a specific hook, and its used only twice, so its basically a code shortcut.

its fine to keep it, but lets move it out of the app level hooks, and maybe inside the hometabs/albums dir, where it is used.

2022-07-15 12:42 UTC, pvinis commented on src/app/hooks/useArtworksByMode.tsx
> +}
true. or even null specifically. its good to type the return type of our hooks, so we are sure we code what we expect.

2022-07-15 12:43 UTC, pvinis commented on src/app/sharedUI/Header.tsx
> +              backButtonAction?.()
nice

2022-07-15 12:45 UTC, pvinis commented on src/app/store/Models/AlbumsModel.tests.tsx
> +    it("updates name and new artworks Id", () => {
```suggestion
    it("updates name and new artwork ids", () => {
```

2022-07-15 12:49 UTC, rajsam003 commented on src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
> +        backButtonAction={backButtonAction}
This is so true 😅 I didn't think about it. 🙆🏽‍♀️

2022-07-15 12:50 UTC, rajsam003 commented on src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
> +        backButtonAction={backButtonAction}
Do you have any suggestions? 
Should I use something like `useFocusEffect()` ?

2022-07-15 12:51 UTC, pvinis commented on src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
> +        albumName: mode === "edit" ? album?.name || "" : "",
yep. we should never use `||` in our code when we can use `??` instead.

2022-07-15 12:55 UTC, pvinis commented on src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
> +        backButtonAction={backButtonAction}
thats probably a good way to do this. Though I would suggest to do this as a separate PR and ticket, so that we can put this in the Header, and have it hook into the hw back of android, as well as the backswipe.
🤔  what do we think? here is also ok, it just feels separate enough to be done in a new PR.

2022-07-15 12:55 UTC, dimatretyak commented on src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
> +        backButtonAction={backButtonAction}
unfortunately, `useFocusEffect` will not work correctly

https://user-images.githubusercontent.com/3513494/179227127-d4c59e45-8ee0-4483-a076-e2351997a036.mp4

2022-07-15 12:55 UTC, pvinis requested changes
just marking this as req changes, as we discussed in the comments here and on slack

2022-07-15 12:56 UTC, dimatretyak commented on src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
> +        backButtonAction={backButtonAction}
> can put this in the Header, and have it hook into the hw back of android, as well as the backswipe.
🤔 what do we think? here is also ok, it just feels separate enough to be done in a new PR

I agree with this 👌

2022-07-15 13:01 UTC, dimatretyak commented on src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
> +        backButtonAction={backButtonAction}
> Do you have any suggestions

Maybe we can use just `useEffect` 

```javascript
useEffect(() => {
  if (mode === "edit") {
    GlobalStore.actions.albums.selectArtworksForAnExistingAlbum(null)
  }
}, [])
```

2022-07-15 13:06 UTC, dimatretyak commented on src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
> +        backButtonAction={backButtonAction}
or we just have to store the data in the local store for `CreateOrEditAlbum` in `edit` mode. And every time we render this screen, we will have a local store with an initial state

2022-07-15 13:10 UTC, rajsam003 commented on src/app/hooks/useArtworksByMode.tsx
> +export const useArtworksByMode = (mode: "create" | "edit", slug?: string) => {
I agree with the hook usage but I dont prefer moving it to `hometabs/albums` because then it will go inside the `screens` folder that will not follow the project structure pattern.

2022-07-18 09:30 UTC, rajsam003 commented on src/app/screens/HomeTabs/Albums/CreateOrEditAlbum/CreateOrEditAlbum.tsx
> +        backButtonAction={backButtonAction}
Now instead of clearing it with backbuttonAction. I am clearing it when clicking on edit button. What do you think?

2022-07-18 09:33 UTC, rajsam003 commented on src/app/screens/HomeTabs/Albums/AlbumArtworks.tsx
> +  }
Here @pvinis @dimatretyak 
Let me know if its a good workaround.

2022-07-18 10:28 UTC, pvinis commented on src/app/screens/HomeTabs/Albums/AlbumArtworks.tsx
> +      "You cannot undo this action",
```suggestion
      "You cannot undo this action.",
```

2022-07-18 10:29 UTC, merged